In [9]:
#Import dependencies
import pandas as pd

#Import csv data and use Pandas to create a Data Frame
df = pd.read_csv("../Resources/Original_CVD.csv")
df

,General_Health,Checkup,Exercise,Heart_Disease,Skin_Cancer,Other_Cancer,Depression,Diabetes,Arthritis,Sex,Age_Category,Height_(cm),Weight_(kg),BMI,Smoking_History,Alcohol_Consumption,Fruit_Consumption,Green_Vegetables_Consumption,FriedPotato_Consumption
0,Poor,Within the past 2 years,No,No,No,No,No,No,Yes,Female,70-74,150.0,32.66,14.54,Yes,0.0,30.0,16.0,12.0
1,Very Good,Within the past year,No,Yes,No,No,No,Yes,No,Female,70-74,165.0,77.11,28.29,No,0.0,30.0,0.0,4.0
2,Very Good,Within the past year,Yes,No,No,No,No,Yes,No,Female,60-64,163.0,88.45,33.47,No,4.0,12.0,3.0,16.0
3,Poor,Within the past year,Yes,Yes,No,No,No,Yes,No,Male,75-79,180.0,93.44,28.73,No,0.0,30.0,30.0,8.0
4,Good,Within the past year,No,No,No,No,No,No,No,Male,80+,191.0,88.45,24.37,Yes,0.0,8.0,4.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
308849,Very Good,Within the past year,Yes,No,No,No,No,No,No,Male,25-29,168.0,81.65,29.05,No,4.0,30.0,8.0,0.0
308850,Fair,Within the past 5 years,Yes,No,No,No,No,Yes,No,Male,65-69,180.0,69.85,21.48,No,8.0,15.0,60.0,4.0
308851,Very Good,5 or more years ago,Yes,No,No,No,Yes,"Yes, but female told only during pregnancy",No,Female,30-34,157.0,61.23,24.69,Yes,4.0,40.0,8.0,4.0
308852,Very Good,Within the past year,Yes,No,No,No,No,No,No,Male,65-69,183.0,79.38,23.73,No,3.0,30.0,12.0,0.0
308853,Excellent,Within the past year,Yes,No,No,No,No,No,No,Female,45-49,160.0,81.19,31.71,No,1.0,5.0,12.0,1.0

In [10]:
#Rename Columns to be more natural 
df = df.rename(columns = {
    'General_Health': 'General Health',
    'Heart_Disease': 'Heart Disease',
    'Skin_Cancer': 'Skin Cancer',
    'Other_Cancer': 'Other Cancer',
    'Age_Category': 'Age Category',
    'Height_(cm)': 'Height (cm)',
    'Weight_(kg)':'Weight (kg)', 
    'Smoking_History':'Smoking History',
    'Alcohol_Consumption':'Alcohol (Servings/Month)', 
    'Fruit_Consumption':'Fruit (Servings/Month)',
    'Green_Vegetables_Consumption': 'Green Vegetables (Servings/Month)', 
    'FriedPotato_Consumption': 'Fried Potato (Servings/Month)'
})

#Check for null rows and drop any:
df.dropna()

#Checked for odd values using .unique() 
#Identified desirable changes in the columns edited below

#Change the Last Checkup Column to be quickly readable
df["Checkup"] = df["Checkup"].replace("Within the past year", "<1" )
df["Checkup"] = df["Checkup"].replace("Within the past 2 years", "<2" )
df["Checkup"] = df["Checkup"].replace("Within the past 5 years", "<5" )
df["Checkup"] = df["Checkup"].replace("5 or more years ago", "5+" )

#Change the Diabetes Column to have simpler answers
df['Diabetes']=df['Diabetes'].replace({"No":"None", \
                                       "No, pre-diabetes or borderline diabetes":"Pre-diabetes or Borderline", \
                                        "Yes, but female told only during pregnancy":"Pregnacy-Induced"})

In [11]:
#Export the Data frame to a csv for use in data analysis
df.to_csv("../Resources/Cleaned_CVD.csv", index=False)

In [12]:
#Group by Heart Disease Status
grouped_df = df.groupby(["Heart Disease"])
grouped_df.count()

,General Health,Checkup,Exercise,Skin Cancer,Other Cancer,Depression,Diabetes,Arthritis,Sex,Age Category,Height (cm),Weight (kg),BMI,Smoking History,Alcohol (Servings/Month),Fruit (Servings/Month),Green Vegetables (Servings/Month),Fried Potato (Servings/Month)
Heart Disease,,,,,,,,,,,,,,,,,,
No,283883,283883,283883,283883,283883,283883,283883,283883,283883,283883,283883,283883,283883,283883,283883,283883,283883,283883
Yes,24971,24971,24971,24971,24971,24971,24971,24971,24971,24971,24971,24971,24971,24971,24971,24971,24971,24971